In [2]:
import requests
from bs4 import BeautifulSoup

In [3]:
url='https://storage.googleapis.com/kagglesdsdata/datasets/2299751/3868917/dataset_book.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240512%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240512T221712Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=5826e8107fdb12a202ada6a68af612647e86d6fe2ba6744c8a1c7fa818db8a1a51c9c6230b2b93a6331bfce536f27d496887108c85446704b1f919db5d4ee7651d46778e4ab3b56465af80e4e3e3f7fff27198f6fcb638246f10a839d93a62f2aebb34df9540dc4cbef84d72fb7cad82f7633d25f45ee13472774f52a3d05dc03e83eb1d082c6af64baa88dd8d435de3e4e512d6eb93941894adcaad1344b58196979c420a49c5e07deb20d3c59b5006a1eba3428ea9c53d1c39035d6347d53c20cfe3bcb5f307f0bbc1611fd4d9a71309e35453040e895b07ce3fc33b9447df46b02f70d313ec97df01f1d914bf1f07e3363ba158040c987e7ee74b84699d6e'

In [4]:
content=requests.get(url)

In [5]:
data=content.content

In [6]:
data

b'\xef\xbb\xbf\r\n\r\n      It is a truth universally acknowledged, that a single man in\r\n      possession of a good fortune, must be in want of a wife.\r\n\r\n      However little known the feelings or views of such a man may be\r\n      on his first entering a neighbourhood, this truth is so well\r\n      fixed in the minds of the surrounding families, that he is\r\n      considered as the rightful property of some one or other of their\r\n      daughters.\r\n\r\n      \xe2\x80\x9cMy dear Mr. Bennet,\xe2\x80\x9d said his lady to him one day, \xe2\x80\x9chave you\r\n      heard that Netherfield Park is let at last?\xe2\x80\x9d\r\n\r\n      Mr. Bennet replied that he had not.\r\n\r\n      \xe2\x80\x9cBut it is,\xe2\x80\x9d returned she; \xe2\x80\x9cfor Mrs. Long has just been here, and\r\n      she told me all about it.\xe2\x80\x9d\r\n\r\n      Mr. Bennet made no answer.\r\n\r\n      \xe2\x80\x9cDo not you want to know who has taken it?\xe2\x80\x9d cried his wife\r\n      impatiently

In [7]:
soup=BeautifulSoup(data,"html.parser")

In [8]:
corpus=""
corpus=corpus.join(soup)

In [9]:
corpus

'\r\n\r\n      It is a truth universally acknowledged, that a single man in\r\n      possession of a good fortune, must be in want of a wife.\r\n\r\n      However little known the feelings or views of such a man may be\r\n      on his first entering a neighbourhood, this truth is so well\r\n      fixed in the minds of the surrounding families, that he is\r\n      considered as the rightful property of some one or other of their\r\n      daughters.\r\n\r\n      “My dear Mr. Bennet,” said his lady to him one day, “have you\r\n      heard that Netherfield Park is let at last?”\r\n\r\n      Mr. Bennet replied that he had not.\r\n\r\n      “But it is,” returned she; “for Mrs. Long has just been here, and\r\n      she told me all about it.”\r\n\r\n      Mr. Bennet made no answer.\r\n\r\n      “Do not you want to know who has taken it?” cried his wife\r\n      impatiently.\r\n\r\n      “_You_ want to tell me, and I have no objection to hearing it.”\r\n\r\n      This was invitation enough.\r\n

In [10]:
import re

In [11]:
corpus=re.sub('[^a-zA-Z0-9]'," ",corpus)

In [12]:
corpus

'          It is a truth universally acknowledged  that a single man in        possession of a good fortune  must be in want of a wife           However little known the feelings or views of such a man may be        on his first entering a neighbourhood  this truth is so well        fixed in the minds of the surrounding families  that he is        considered as the rightful property of some one or other of their        daughters            My dear Mr  Bennet   said his lady to him one day   have you        heard that Netherfield Park is let at last            Mr  Bennet replied that he had not            But it is   returned she   for Mrs  Long has just been here  and        she told me all about it            Mr  Bennet made no answer            Do not you want to know who has taken it   cried his wife        impatiently             You  want to tell me  and I have no objection to hearing it            This was invitation enough            Why  my dear  you must know  Mrs  Long says t

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [14]:
tokenizer=Tokenizer()

In [15]:
tokenizer.fit_on_texts([corpus])

In [16]:
words=tokenizer.texts_to_sequences([corpus])[0]

In [17]:
tokenizer.index_word


{1: 'the',
 2: 'to',
 3: 'of',
 4: 'and',
 5: 'her',
 6: 'i',
 7: 'a',
 8: 'in',
 9: 'was',
 10: 'she',
 11: 'that',
 12: 'it',
 13: 'not',
 14: 'you',
 15: 'he',
 16: 'his',
 17: 'be',
 18: 'as',
 19: 'had',
 20: 'with',
 21: 'for',
 22: 'but',
 23: 'is',
 24: 'have',
 25: 'at',
 26: 'mr',
 27: 'him',
 28: 'on',
 29: 'my',
 30: 's',
 31: 'by',
 32: 'all',
 33: 'elizabeth',
 34: 'they',
 35: 'so',
 36: 'were',
 37: 'which',
 38: 'could',
 39: 'been',
 40: 'from',
 41: 'no',
 42: 'very',
 43: 'this',
 44: 'what',
 45: 'would',
 46: 'your',
 47: 'me',
 48: 'their',
 49: 'them',
 50: 'will',
 51: 'darcy',
 52: 'said',
 53: 'such',
 54: 'or',
 55: 'when',
 56: 'if',
 57: 'an',
 58: 'do',
 59: 'are',
 60: 'there',
 61: 'mrs',
 62: 'much',
 63: 'bennet',
 64: 'am',
 65: 'more',
 66: 'must',
 67: 'any',
 68: 'bingley',
 69: 'jane',
 70: 'who',
 71: 'than',
 72: 'miss',
 73: 'one',
 74: 'did',
 75: 'we',
 76: 'should',
 77: 'know',
 78: 'how',
 79: 'before',
 80: 'herself',
 81: 'other',
 82: 

In [18]:
tokenizer.lower

True

In [19]:
words

[12,
 23,
 7,
 543,
 2501,
 706,
 11,
 7,
 1012,
 117,
 8,
 1160,
 3,
 7,
 95,
 384,
 66,
 17,
 8,
 350,
 3,
 7,
 335,
 125,
 102,
 282,
 1,
 181,
 54,
 1084,
 3,
 53,
 7,
 117,
 93,
 17,
 28,
 16,
 119,
 1248,
 7,
 516,
 43,
 543,
 23,
 35,
 83,
 656,
 8,
 1,
 2133,
 3,
 1,
 3100,
 1500,
 11,
 15,
 23,
 631,
 18,
 1,
 4062,
 1161,
 3,
 90,
 73,
 54,
 81,
 3,
 48,
 323,
 29,
 114,
 26,
 63,
 52,
 16,
 101,
 2,
 27,
 73,
 120,
 24,
 14,
 182,
 11,
 214,
 657,
 23,
 208,
 25,
 140,
 26,
 63,
 153,
 11,
 15,
 19,
 13,
 22,
 12,
 23,
 351,
 10,
 21,
 61,
 143,
 84,
 219,
 39,
 235,
 4,
 10,
 236,
 47,
 32,
 129,
 12,
 26,
 63,
 133,
 41,
 252,
 58,
 13,
 14,
 350,
 2,
 77,
 70,
 84,
 489,
 12,
 174,
 16,
 335,
 1867,
 14,
 350,
 2,
 225,
 47,
 4,
 6,
 24,
 41,
 872,
 2,
 606,
 12,
 43,
 9,
 445,
 151,
 311,
 29,
 114,
 14,
 66,
 77,
 61,
 143,
 873,
 11,
 214,
 23,
 489,
 31,
 7,
 130,
 117,
 3,
 632,
 384,
 40,
 1,
 1501,
 3,
 1868,
 11,
 15,
 176,
 215,
 28,
 1249,
 8,
 7,
 1085,
 4,
 43

In [20]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'of': 3,
 'and': 4,
 'her': 5,
 'i': 6,
 'a': 7,
 'in': 8,
 'was': 9,
 'she': 10,
 'that': 11,
 'it': 12,
 'not': 13,
 'you': 14,
 'he': 15,
 'his': 16,
 'be': 17,
 'as': 18,
 'had': 19,
 'with': 20,
 'for': 21,
 'but': 22,
 'is': 23,
 'have': 24,
 'at': 25,
 'mr': 26,
 'him': 27,
 'on': 28,
 'my': 29,
 's': 30,
 'by': 31,
 'all': 32,
 'elizabeth': 33,
 'they': 34,
 'so': 35,
 'were': 36,
 'which': 37,
 'could': 38,
 'been': 39,
 'from': 40,
 'no': 41,
 'very': 42,
 'this': 43,
 'what': 44,
 'would': 45,
 'your': 46,
 'me': 47,
 'their': 48,
 'them': 49,
 'will': 50,
 'darcy': 51,
 'said': 52,
 'such': 53,
 'or': 54,
 'when': 55,
 'if': 56,
 'an': 57,
 'do': 58,
 'are': 59,
 'there': 60,
 'mrs': 61,
 'much': 62,
 'bennet': 63,
 'am': 64,
 'more': 65,
 'must': 66,
 'any': 67,
 'bingley': 68,
 'jane': 69,
 'who': 70,
 'than': 71,
 'miss': 72,
 'one': 73,
 'did': 74,
 'we': 75,
 'should': 76,
 'know': 77,
 'how': 78,
 'before': 79,
 'herself': 80,
 'other': 81,
 'tho

In [21]:
import numpy as np
x = []
y = []

for i in range(3, len(words)):
    x.append(words[i-3:i])
    y.append(words[i])



In [22]:
x = np.array(x)
y = np.array(y)

print("The Length of x and y are:", len(x), len(y))

The Length of x and y are: 125961 125961


In [23]:
x

array([[  12,   23,    7],
       [  23,    7,  543],
       [   7,  543, 2501],
       ...,
       [6587,    2,  229],
       [   2,  229,  129],
       [ 229,  129,  563]])

In [24]:
y

array([ 543, 2501,  706, ...,  129,  563, 1671])

In [25]:
total_words=len(tokenizer.word_index)+1

In [26]:
import tensorflow
y=tensorflow.keras.utils.to_categorical(y,num_classes=total_words)

In [27]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [28]:
from tensorflow.keras.utils import pad_sequences
x=tensorflow.keras.utils.pad_sequences(x,maxlen=500,padding='pre')

In [53]:
x[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [54]:
y[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=50)

In [32]:
x_train.shape

(75576, 500)

In [33]:
x_test.shape

(50385, 500)

In [34]:
y_train.shape

(75576, 6588)

In [35]:
y_test.shape

(50385, 6588)

In [44]:
from tensorflow.keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.models import Sequential

In [45]:
model=Sequential()

In [46]:
model.add(Embedding(total_words,10,input_length=500))

In [47]:
model.add(LSTM(1000))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))

In [48]:
model.add(Dense(total_words,activation='softmax'))

In [49]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 500, 10)           65880     
                                                                 
 lstm_1 (LSTM)               (None, 500, 1000)         4044000   
                                                                 
 lstm_2 (LSTM)               (None, 1000)              8004000   
                                                                 
 dense_1 (Dense)             (None, 1000)              1001000   
                                                                 
 dense_2 (Dense)             (None, 6588)              6594588   
                                                                 
Total params: 19709468 (75.19 MB)
Trainable params: 19709468 (75.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [52]:
model.fit(x_train,y_train,epochs=70,validation_split=0.3,verbose=1,batch_size=62)

Epoch 1/70
213/854 [======>.......................] - ETA: 1:30:18 - loss: 6.5739 - accuracy: 0.0332

KeyboardInterrupt: 